public class MyFirstClass {

    public MyFirstClass(){
        takeShower();
        haveBreakFast();
        carServicing();
        moviewithGF();
    }
    
    public static void takeShower(){
        System.debug('I am going fro shower');
    }
    
    public static void haveBreakFast(){
        system.debug('i am having Breakfast');
    }
    
    @future
    Public static void carServicing(){
         system.debug('car being repaired');
    }
   
    public static void moviewithGF(){
        system.debug('Watching movie with GF');
    }
}